### ISSUE TITLE
Since last update Nuproj dont load in VS (incompatible project)

### ISSUE THREAD

**Issue by Axel3232** [nuproj/nuproj#253]
Hi, 

Since last update, my 2 nuproj projects in my sln dont load anymore it says : "incompatible"
In the VS Log I can see : 
` <entry>
    <record>97</record>
    <time>2016/07/18 18:46:06.724</time>
    <type>Error</type>
 <source>Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost</source>  <description>Still unable to load MEF component DLL: Impossible de charger le fichier ou l&apos;assembly &apos;NuProj.ProjectSystem.14.dll&apos; ou une de ses d&#x00E9;pendances. Le fichier sp&#x00E9;cifi&#x00E9; est introuvable.</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\NUGET\NUPROJ\NuProj.ProjectSystem.14.dll</path>
  </entry>`

Its in French, in english it says : "unable to load NuProj.ProjectSystem.14.dll or one of its dependency. The specified file has not been found"

Note that NuProj.ProjectSystem.14.dll is present in the specified directory.

Here is my VS version  : 
Microsoft Visual Studio Enterprise 2015  FRENCH
Version 14.0.25422.01 Update 3
Microsoft .NET Framework
Version 4.6.01038

Thx

**Comment by AArnott** [comment]
Thanks for your report, @Axel3232. When you say "since last update" can you please specify which version you last used that worked, and which version you upgraded to when it stopped working? We've released twice in the last week so I'm trying to narrow down where the regression occurred.

**Comment by Axel3232** [comment]
Hi, 
You are welcome :)
I updated yesterday so it should be the 0.11.14-beta, the previous version I had was installed a while ago so I guess it was 0.9.3-beta.

Note that for completely other reason I had to reinstall my machine today, I'll try a fresh install with the latest version, I'll keep you posted if it still broken.

**Comment by Axel3232** [comment]
Still the same error with a fresh install of vs 2015 update 3

**Comment by bryan-c-oconnell** [comment]
I'm having difficulty loading my NuProj projects after installing the latest version of the VS extension this morning. I have VS 2015 Update 2. 

![nuproj-vs-error](https://cloud.githubusercontent.com/assets/6117822/16958174/1b93d73a-4da5-11e6-81cd-69711de15d42.PNG)

I'm also no longer able to create a new NuProj project in an existing solution. 

![nuproj-create](https://cloud.githubusercontent.com/assets/6117822/16958186/2117e5e8-4da5-11e6-8b6e-e88e03e9f330.PNG)

**Comment by kovalikp** [comment]
Have you changed paths to `NuProj.props` and `NuProj.targets` in your project by any chance? By default it should something like:

```xml
  <PropertyGroup>
    <NuProjPath Condition=" '$(NuProjPath)' == '' ">$(MSBuildExtensionsPath)\NuProj\</NuProjPath>
  </PropertyGroup>
  <Import Project="$(NuProjPath)\NuProj.props" Condition="Exists('$(NuProjPath)\NuProj.props')" />
  ...
  <Import Project="$(NuProjPath)\NuProj.targets" />
```

**Comment by bryan-c-oconnell** [comment]
@kovalikp - I did have a different path entered for the `<NuProjPath>` element. I switched that to match the default you provided and tried to reload the project, in VS, but got the same errors.

The other two nodes you listed match what I have in my .nuproj file.

**Comment by bryan-c-oconnell** [comment]
UPDATE: Yesterday, one of my teammates installed the latest version of the extension as well, and it worked fine for him. He had VS 2015 Update 3 though. So this morning I installed VS 2015 Update 3, and my problems have gone away.

**Comment by AArnott** [comment]
Interesting. I'm not aware of a dependency we have on Update 3. That's an interesting thing to keep in mind though and I'll watch for other reports to see if we need to change something to avoid that requirement.
It sounds like everyone's issues are resolved. So I'm closing the issue.

**Comment by kovalikp** [comment]
Does @Axel3232 still experiences the problem? Can we actually close this?

**Comment by AArnott** [comment]
@Axel3232's last comment was:

> Note that if I had a new Nuget package project it works.... so I'll recreate my nuget projects

**Comment by kovalikp** [comment]
Ah, missed that. Nvm.

**Comment by Axel3232** [comment]
Hi, I recreated all my nuproj so I don't have any problems anymore.
Anyway thx for looking into that.
